INSERT INTO TB_PRODUCT (NAME,PRICE) VALUES ('Harley Quinn: Birds of Prey',30);
INSERT INTO TB_PRODUCT (NAME,PRICE) VALUES ('Sonic the Hedgedhog',30);
INSERT INTO TB_PRODUCT (NAME,PRICE) VALUES ('Mulan',30);